### ISSUE TITLE
Add anko to declare layout

### ISSUE THREAD

**Issue by hantsy** [gs666/XimalayaKotlin#6]
Check it here, 

https://github.com/Kotlin/anko

Use Kotlin DSL to describe the layout instead of Android XML.

**Comment by Forsaken-sl** [comment]
你好，请问为什么一定要用anko来写布局呢？
曾经也看过anko，但是感觉没办法实时预览，有时候实在感觉很乏力。
另外，现在constraintLayout感觉很好用啊。

**Comment by Forsaken-sl** [comment]
> Check it here,
> 
> https://github.com/Kotlin/anko
> 
> Use Kotlin DSL to describe the layout instead of Android XML.

你好，请问为什么一定要用anko来写布局呢？
曾经也看过anko，但是感觉没办法实时预览，有时候实在感觉很乏力。
另外，现在constraintLayout感觉很好用啊。

**Comment by hantsy** [comment]
只是建议，供参考。我觉得这是一个很Cool特性。和 Flutter有点类似，代码和布局用一种语言解决。就 如 Spring 5.0 以后加入大量的 Kotlin DSL 支持一样，当使用 Kotlin 开发的时候发现用它代码看起来比较舒服。

**Comment by gs666** [comment]
事实上，我目前更喜欢 XML 写布局。我只了解一点anko的知识，不知道anko有没有优化Android适配的难题呢？以后会尝试深入学习anko

**Comment by hantsy** [comment]
我觉得这种混合方式，可能动态的修改布局（比如屏幕适配）会容易一些。

**Comment by hantsy** [comment]
每个ISSUE 不一定要去实现，有时只是不同人的想法。
